"""Causal Synthetic Data Loader.

Downloads counterfactual synthetic financial data from a public S3 bucket.
The data is generated by an external causal SDE (Stochastic Differential
Equation) pipeline that is outside the scope of this repository.

The generated CSV preserves market stylized facts — volatility clustering,
heavy-tailed distributions, regime switches — while providing unlimited
out-of-sample evaluation paths with zero data leakage.
"""

import os
import urllib.request

import pandas as pd

# Public HTTPS URL — no credentials required.
DEFAULT_URL = "https://anonymous-submission--0-public.s3.us-east-1.amazonaws.com/csde-output-1/csde-1.csv"


class CausalSyntheticGenerator:
    """Downloads and caches causal synthetic financial data."""

    def __init__(self, url: str = DEFAULT_URL, cache_dir: str = "data/generators/cache"):
        self.url = url
        self.cache_path = os.path.join(cache_dir, "csde_cache.csv")
        os.makedirs(cache_dir, exist_ok=True)

        self.data = self._load_data()
        self._parse_bounds()

    def _load_data(self) -> pd.DataFrame:
        if os.path.exists(self.cache_path):
            print(f"Loading synthetic data from local cache: {self.cache_path}")
            return pd.read_csv(self.cache_path)

        print(f"Downloading synthetic data from {self.url}...")
        urllib.request.urlretrieve(self.url, self.cache_path)
        return pd.read_csv(self.cache_path)

    def _parse_bounds(self):
        if "Ticker" not in self.data.columns or "Date" not in self.data.columns:
            raise KeyError("Dataset must contain 'Ticker' and 'Date' columns.")

        self.available_tickers = set(self.data["Ticker"].unique())
        self.data["Date"] = pd.to_datetime(self.data["Date"])
        self.data = self.data.set_index("Date")
        self.available_dates = self.data.index.dropna().unique()
        self.min_date = self.available_dates.min()
        self.max_date = self.available_dates.max()

    def fetch(self, tickers: list, start_date: str, end_date: str) -> pd.DataFrame:
        """Retrieve a slice of the synthetic dataset.

        Raises ValueError if requested tickers or dates are out of bounds.
        """
        missing = [t for t in tickers if t not in self.available_tickers]
        if missing:
            raise ValueError(
                f"Tickers not in synthetic set: {missing}. "
                f"Available (sample): {list(self.available_tickers)[:10]}"
            )

        start_ts = pd.to_datetime(start_date)
        end_ts = pd.to_datetime(end_date)
        if start_ts < self.min_date or end_ts > self.max_date:
            raise ValueError(
                f"Date range ({start_date} to {end_date}) outside dataset bounds "
                f"({self.min_date.date()} to {self.max_date.date()})."
            )

        mask = (self.data.index >= start_ts) & (self.data.index <= end_ts)
        return self.data[mask & self.data["Ticker"].isin(tickers)]
