"""
Step Logger - logs every agent node execution to structured files.

Creates a timestamped run directory under `agent_logs/` with:
  - steps.jsonl   : one JSON line per node execution (chronological)
  - hypotheses.md : hypotheses in human-readable format
  - generated_code.py : the code generated by the code_generator node
  - code_execution.log : stdout/stderr from code execution
  - router_decisions.log : data_analyst routing decisions
"""

import os
import json
import logging
from datetime import datetime
from typing import Any, Optional

logger = logging.getLogger(__name__)

_LOGS_ROOT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "logs")


class StepLogger:
    """Singleton-style logger for a single agent run."""

    def __init__(self, run_dir: Optional[str] = None):
        if run_dir:
            self.run_dir = run_dir
        else:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            self.run_dir = os.path.join(_LOGS_ROOT, f"run_{timestamp}")

        os.makedirs(self.run_dir, exist_ok=True)
        self._step_counter = 0
        logger.info(f"StepLogger initialised – writing to {self.run_dir}")

    # ------------------------------------------------------------------
    # Generic step logging
    # ------------------------------------------------------------------
    def log_step(self, node_name: str, data: dict[str, Any] | None = None):
        """Append a line to steps.jsonl."""
        self._step_counter += 1
        entry = {
            "step": self._step_counter,
            "timestamp": datetime.now().isoformat(),
            "node": node_name,
            **(data or {}),
        }
        path = os.path.join(self.run_dir, "steps.jsonl")
        with open(path, "a") as f:
            f.write(json.dumps(entry, ensure_ascii=False) + "\n")

    # ------------------------------------------------------------------
    # Hypothesis-specific logging
    # ------------------------------------------------------------------
    def log_hypotheses(self, hypotheses: list[str]):
        """Write hypotheses to a readable Markdown file."""
        path = os.path.join(self.run_dir, "hypotheses.md")
        with open(path, "w") as f:
            f.write("# Hypotheses Generated\n\n")
            f.write(f"_Logged at {datetime.now().isoformat()}_\n\n")
            for h in hypotheses:
                f.write(f"{h}\n\n---\n\n")
        self.log_step("hypothesis_maker", {"hypotheses_count": len(hypotheses), "hypotheses": hypotheses})

    def log_panelist_hypotheses(self, label: str, hypotheses: list[dict]):
        """
        Write one Markdown file per panelist with its raw hypotheses.

        Parameters
        ----------
        label : str
            Panelist label, e.g. ``"ollama/qwen2.5:14b"``.
        hypotheses : list[dict]
            Each dict has keys: hypothesis, rationale, key_factors, possible_tests.
        """
        safe = label.replace("/", "_").replace(":", "_").replace(" ", "_")
        path = os.path.join(self.run_dir, f"hypotheses_{safe}.md")
        with open(path, "w") as f:
            f.write(f"# Hypotheses — Panelist: {label}\n\n")
            f.write(f"_Logged at {datetime.now().isoformat()}_\n\n")
            f.write(f"**Total: {len(hypotheses)}**\n\n")
            for i, h in enumerate(hypotheses, 1):
                f.write(f"### Hypothesis {i}\n")
                f.write(f"**Hypothesis:** {h['hypothesis']}\n")
                f.write(f"**Rationale:** {h['rationale']}\n")
                f.write("**Key Factors:**\n")
                for kf in h.get("key_factors", []):
                    f.write(f"   - {kf}\n")
                f.write("**Possible Tests:**\n")
                for pt in h.get("possible_tests", []):
                    f.write(f"   - {pt}\n")
                f.write("\n---\n\n")

    def log_peer_review(self, review_stats: dict, pre_count: int, post_count: int):
        """Write peer-review results to a dedicated Markdown file."""
        path = os.path.join(self.run_dir, "peer_review.md")
        with open(path, "w") as f:
            f.write("# Peer Review Results\n\n")
            f.write(f"_Logged at {datetime.now().isoformat()}_\n\n")
            f.write(f"**Before review:** {pre_count} hypotheses\n")
            f.write(f"**After review:** {post_count} hypotheses\n\n")

            if "error" in review_stats:
                f.write(f"⚠️ Review failed: {review_stats['error']}\n\n")
                return

            for section, title in [("kept", "✅ KEPT"), ("dropped", "❌ DROPPED")]:
                entries = review_stats.get(section, [])
                if not entries:
                    continue
                f.write(f"## {title} ({len(entries)})\n\n")
                for e in entries:
                    f.write(f"### Hypothesis {e['index']}\n")
                    f.write(
                        f"| Relevance | Testability | Specificity | Novelty | **Avg** |\n"
                        f"|:---------:|:-----------:|:-----------:|:-------:|:-------:|\n"
                        f"| {e['relevance']} | {e['testability']} | {e['specificity']} "
                        f"| {e['novelty']} | **{e['avg']}** |\n\n"
                    )
                    f.write(f"**Verdict:** {e['verdict']} — {e['reasoning']}\n\n---\n\n")

    def log_adversarial(self, adversarial_stats: dict, pre_count: int, post_count: int):
        """Write adversarial-defence results to a dedicated Markdown file."""
        path = os.path.join(self.run_dir, "adversarial_defence.md")
        with open(path, "w") as f:
            f.write("# Adversarial Defence Results\n\n")
            f.write(f"_Logged at {datetime.now().isoformat()}_\n\n")
            f.write(f"**Before defence:** {pre_count} hypotheses\n")
            f.write(f"**After defence:** {post_count} hypotheses\n\n")

            if "error_challenge" in adversarial_stats:
                f.write(f"⚠️ Challenge phase failed: {adversarial_stats['error_challenge']}\n\n")
                return
            if "error_defence" in adversarial_stats:
                f.write(f"⚠️ Defence phase failed: {adversarial_stats['error_defence']}\n\n")

            f.write(f"- Total challenges: {adversarial_stats.get('total_challenges', '?')}\n")
            f.write(f"- HIGH-severity: {adversarial_stats.get('high_severity', '?')}\n")
            f.write(f"- Dropped: {adversarial_stats.get('dropped', 0)}\n")
            f.write(f"- Revised: {adversarial_stats.get('revised', 0)}\n")
            f.write(f"- Survived: {adversarial_stats.get('survived', post_count)}\n")

    # ------------------------------------------------------------------
    # Router decision logging
    # ------------------------------------------------------------------
    def log_router_decision(self, next_node: str, reasoning: str, state_summary: dict):
        """Log a data_analyst routing decision."""
        path = os.path.join(self.run_dir, "router_decisions.log")
        with open(path, "a") as f:
            f.write(f"[{datetime.now().isoformat()}] -> {next_node}\n")
            f.write(f"  Reasoning: {reasoning}\n")
            f.write(f"  State: {json.dumps(state_summary, ensure_ascii=False)}\n\n")
        self.log_step("data_analyst", {"decision": next_node, "reasoning": reasoning})

    # ------------------------------------------------------------------
    # Code generation logging
    # ------------------------------------------------------------------
    def log_generated_code(self, code: str):
        """Save the generated Python code."""
        path = os.path.join(self.run_dir, "generated_code.py")
        with open(path, "w") as f:
            f.write(f"# Auto-generated at {datetime.now().isoformat()}\n\n")
            f.write(code)
        self.log_step("code_generator", {"code_length": len(code)})

    # ------------------------------------------------------------------
    # Code execution logging
    # ------------------------------------------------------------------
    def log_code_execution(self, output: str, error: str, new_plots: list[str]):
        """Log execution stdout/stderr and generated plots."""
        path = os.path.join(self.run_dir, "code_execution.log")
        with open(path, "w") as f:
            f.write(f"=== Execution at {datetime.now().isoformat()} ===\n\n")
            f.write("--- STDOUT ---\n")
            f.write(output or "(empty)")
            f.write("\n\n--- STDERR ---\n")
            f.write(error or "(empty)")
            f.write("\n\n--- PLOTS GENERATED ---\n")
            f.write("\n".join(new_plots) if new_plots else "(none)")
            f.write("\n")
        self.log_step("code_executor", {
            "has_error": bool(error),
            "plots_generated": new_plots,
        })

    # ------------------------------------------------------------------
    # Report logging
    # ------------------------------------------------------------------
    def log_report(self, report: str):
        """Save a copy of the final report."""
        path = os.path.join(self.run_dir, "final_report.md")
        with open(path, "w") as f:
            f.write(report)
        self.log_step("report_generator", {"report_length": len(report)})

    def log_code_report(self, report: str):
        """Save a copy of the final code-grounded report."""
        path = os.path.join(self.run_dir, "final_code_report.md")
        with open(path, "w") as f:
            f.write(report)
        self.log_step("code_report_generator", {"report_length": len(report)})


# ------------------------------------------------------------------
# Module-level singleton
# ------------------------------------------------------------------
_instance: StepLogger | None = None


def init_step_logger(run_dir: Optional[str] = None) -> StepLogger:
    """Initialise the global StepLogger instance (call once from main)."""
    global _instance
    _instance = StepLogger(run_dir)
    return _instance


def get_step_logger() -> StepLogger | None:
    """Return the global StepLogger, or None if not initialised."""
    return _instance
